
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 02 21:47:29 CEST 2019
//----------------------------------------------------

package practicaspl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 6;
  public static final int function = 17;
  public static final int closeParenthesis = 19;
  public static final int plus = 23;
  public static final int numeric_real_const = 4;
  public static final int mod = 27;
  public static final int minus = 24;
  public static final int INTEGER = 20;
  public static final int do = 39;
  public static final int multiplication = 25;
  public static final int comma = 15;
  public static final int identifier = 2;
  public static final int begin = 9;
  public static final int until = 41;
  public static final int downto = 44;
  public static final int end = 10;
  public static final int else = 37;
  public static final int equal = 12;
  public static final int then = 36;
  public static final int var = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int openParenthesis = 18;
  public static final int or = 28;
  public static final int colon = 14;
  public static final int constant = 11;
  public static final int repeat = 40;
  public static final int procedure = 16;
  public static final int while = 38;
  public static final int if = 35;
  public static final int REAL = 21;
  public static final int greater = 30;
  public static final int lessEqual = 32;
  public static final int for = 42;
  public static final int and = 29;
  public static final int not = 34;
  public static final int numeric_integer_const = 3;
  public static final int less = 31;
  public static final int greaterEqual = 33;
  public static final int string_const = 5;
  public static final int div = 26;
  public static final int semicolon = 7;
  public static final int to = 43;
  public static final int dot = 8;
  public static final int assig = 22;
}

