
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practicapl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int minus = 24;
  public static final int assig = 22;
  public static final int constant = 11;
  public static final int identifier = 2;
  public static final int end = 10;
  public static final int function = 17;
  public static final int numeric_integer_const = 3;
  public static final int procedure = 16;
  public static final int program = 6;
  public static final int semicolon = 7;
  public static final int closeParenthesis = 19;
  public static final int numeric_real_const = 4;
  public static final int div = 26;
  public static final int string_const = 5;
  public static final int EOF = 0;
  public static final int equal = 12;
  public static final int dot = 8;
  public static final int error = 1;
  public static final int plus = 23;
  public static final int colon = 14;
  public static final int INTEGER = 20;
  public static final int openParenthesis = 18;
  public static final int var = 13;
  public static final int REAL = 21;
  public static final int begin = 9;
  public static final int multiplication = 25;
  public static final int mod = 27;
  public static final int comma = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identifier",
  "numeric_integer_const",
  "numeric_real_const",
  "string_const",
  "program",
  "semicolon",
  "dot",
  "begin",
  "end",
  "constant",
  "equal",
  "var",
  "colon",
  "comma",
  "procedure",
  "function",
  "openParenthesis",
  "closeParenthesis",
  "INTEGER",
  "REAL",
  "assig",
  "plus",
  "minus",
  "multiplication",
  "div",
  "mod"
  };
}

