
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practicapl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 7;
  public static final int elseConditional = 38;
  public static final int function = 18;
  public static final int closeParenthesis = 20;
  public static final int plus = 24;
  public static final int numeric_real_const = 2;
  public static final int mod = 28;
  public static final int minus = 25;
  public static final int whileLoop = 39;
  public static final int INTEGER = 21;
  public static final int multiplication = 26;
  public static final int comma = 16;
  public static final int forLoop = 43;
  public static final int identifier = 5;
  public static final int begin = 10;
  public static final int until = 42;
  public static final int downto = 45;
  public static final int end = 11;
  public static final int equal = 13;
  public static final int then = 37;
  public static final int var = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int openParenthesis = 19;
  public static final int or = 29;
  public static final int colon = 15;
  public static final int constant = 12;
  public static final int repeat = 41;
  public static final int procedure = 17;
  public static final int REAL = 22;
  public static final int doFor = 40;
  public static final int greater = 31;
  public static final int lessEqual = 33;
  public static final int unit = 6;
  public static final int not = 35;
  public static final int and = 30;
  public static final int numeric_integer_const = 3;
  public static final int less = 32;
  public static final int greaterEqual = 34;
  public static final int string_const = 4;
  public static final int div = 27;
  public static final int semicolon = 8;
  public static final int to = 44;
  public static final int dot = 9;
  public static final int ifConditional = 36;
  public static final int assig = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numeric_real_const",
  "numeric_integer_const",
  "string_const",
  "identifier",
  "unit",
  "program",
  "semicolon",
  "dot",
  "begin",
  "end",
  "constant",
  "equal",
  "var",
  "colon",
  "comma",
  "procedure",
  "function",
  "openParenthesis",
  "closeParenthesis",
  "INTEGER",
  "REAL",
  "assig",
  "plus",
  "minus",
  "multiplication",
  "div",
  "mod",
  "or",
  "and",
  "greater",
  "less",
  "lessEqual",
  "greaterEqual",
  "not",
  "ifConditional",
  "then",
  "elseConditional",
  "whileLoop",
  "doFor",
  "repeat",
  "until",
  "forLoop",
  "to",
  "downto"
  };
}

